---
framework: mocha
postMerge:
  pattern:
    - "test/test.ts"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "test/test.ts"
preRun:
  - npm i
  - npm run test
postRun:
  - node --version
version: 2.0
